name: sharestream
description: "ShareStream â€” Watch together, instantly."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  media_kit: ^1.2.6
  media_kit_video: ^2.0.1
  media_kit_libs_video: ^1.0.7
  socket_io_client: ^3.0.0
  google_fonts: ^8.0.1
  provider: ^6.1.5+1
  file_picker: ^10.3.10
  uuid: ^4.5.2
  path_provider: ^2.1.5
  flutter_animate: ^4.5.2
  flutter_dotenv: ^6.0.0
  flutter_webrtc: ^1.3.0
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
